version: 2.1

executors:
  python-env:
    docker:
      - 
        image: python:3.7.3-stretch

jobs:
  build:
    executor: python-env
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            make install
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run lint
          command: |
            source venv/bin/activate
            make lint

workflow:
  default:
    jobs:
      - build